### ISSUE TITLE
Does not run with log_to_file = no

### ISSUE THREAD

**Issue by yan12125** [archlinuxcn/lilac#132]
I noticed this when debugging remaining build issues in https://github.com/archlinuxcn/repo/issues/1357.
```
$ ./lilac lib32-check
[D 11-17 16:28:05.953 cmd:47] running ['git', 'reset', '--hard'], not using pty, showing output
HEAD is now at 053906d24c proxmark3-iceman-git: build client tools with flags
[D 11-17 16:28:05.990 cmd:47] running ['git', 'pull', '--no-edit'], not using pty, showing output
Already up to date.
[I 11-17 16:28:10.744 nvchecker:95] Running nvchecker...
[I 11-17 16:28:12.003 core:202] lib32-check: updated to 0.13.0-1
[I 11-17 16:28:12.057 lilac:359] these updated (pkgrel) packages should be rebuilt: None
[I 11-17 16:28:12.058 lilac:361] these previously-failed packages should be rebuilt: None
[I 11-17 16:28:12.058 lilac:363] these packages are updated as detected by nvchecker: {'lib32-check'}
[I 11-17 16:28:12.058 lilac:365] these packages need rebuilding as detected by nvchecker or manually specified: {'lib32-check'}
:: 正在同步軟體包資料庫…
 testing 已經是最新版本
 core 已經是最新版本
 extra 已經是最新版本
 community-testing 已經是最新版本
 community 已經是最新版本
 archlinuxcn 已經是最新版本
[I 11-17 16:28:13.863 lilac:252] building these packages: ['lib32-check']
[D 11-17 16:28:13.864 cmd:47] running ['git', 'reset', '--hard'], not using pty, showing output
HEAD is now at 053906d24c proxmark3-iceman-git: build client tools with flags
[E 11-17 16:28:13.901 lilac:408] unexpected error
    Traceback (most recent call last):
      File "./lilac", line 405, in main
        main_may_raise(D, pkgs_to_build)
      File "./lilac", line 374, in main_may_raise
        start_build(REPO, failed, update_succeeded)
      File "./lilac", line 261, in start_build
        if build_package(logdir, pkg, repo.mods[pkg]):
    NameError: name 'logdir' is not defined
```
I'm fine with toggling log_to_file to yes. Considering the complexity of log handling, removing that option might be better than fixing it.

**Comment by lilydjwg** [comment]
It's gone and logging to file will always be on.
