### ISSUE TITLE
Maintainer checker not working properly?

### ISSUE THREAD

**Issue by swordfeng** [archlinuxcn/lilac#177]
https://github.com/archlinuxcn/repo/blob/147cbf7879297dbde6084a13438d04768fabbd94/archlinuxcn/emacs-queue/lilac.yaml#L6

收到邮件：
```
发生未知错误！调用栈如下：

Traceback (most recent call last):
  File "/home/lilydjwg/soft/lilac/lilac", line 126, in build_package
    lilac_build(
  File "/home/lilydjwg/soft/lilac/lilac2/building.py", line 94, in lilac_build
    pre_build()
  File "<string>", line 2, in pre_build
  File "/home/lilydjwg/soft/lilac/lilac2/api.py", line 492, in aur_pre_build
    raise Exception('unexpected AUR package maintainer / packager', who)
Exception: ('unexpected AUR package maintainer / packager', 'haawda')
```

从 [AUR 页面](https://aur.archlinux.org/packages/emacs-queue/)看，haawda 是 last packager, 不是 maintainer

**Comment by lilydjwg** [comment]
Actually lilac checks last packager for the most time, because that's who that has modified the PKGBUILD. And that's why this field can be a list.

**Comment by swordfeng** [comment]
hmmmm
那我加一下吧 谢谢百合
