### ISSUE TITLE
当PKGEXT存在时lilac会找不到打出来的包

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/lilac#21]
如题
问题出在wps-office的时候
```
PKGEXT=".pkg.tar"
```

```
Traceback (most recent call last):
  File "/home/lilydjwg/bin/lilac", line 111, in build_package
    depends = DEPENDS.get(package, ()),
  File "/home/lilydjwg/soft/lilac/lilaclib.py", line 412, in lilac_build
    raise Exception('no package built')
Exception: no package built
```

**Comment by lilydjwg** [comment]
所以你在 lilac.py 里删掉那行嘛。lilac 只支持 `.pkg.tar.xz` 格式的包。

**Comment by petronny** [comment]
额。。。为什么不是lilac强制设置PKGEXT呢。。。

**Comment by lilydjwg** [comment]
@petronny 怎么强制设置呢？

**Comment by petronny** [comment]
我想错了。。
那我们把所有的后缀都加上呢？
