### ISSUE TITLE
如果上一次lilac运行出错了那么下一次lockit会出权限问题

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/lilac#29]
重现方式
```
$git reset --hard
HEAD is now at c990c5d config.ini: don't override my env variable
$cp config.ini.sample config.ini
$./lilac
[E 09-16 22:34:24.999 lilac:462] unexpected error
    Traceback (most recent call last):
      File "./lilac", line 455, in <module>
        setup()
      File "./lilac", line 450, in setup
        os.chdir(REPODIR)
    FileNotFoundError: [Errno 2] No such file or directory: '/path/to/gitrepo'
$./lilac
[E 09-16 22:34:42.695 lilac:462] unexpected error
    Traceback (most recent call last):
      File "./lilac", line 455, in <module>
        setup()
      File "./lilac", line 440, in setup
        lockit()
      File "./lilac", line 68, in lockit
        lock = os.open(mydir+'/.lock', os.O_WRONLY | os.O_CREAT, 600)
    PermissionError: [Errno 13] Permission denied: '/home/petron/.lilac/.lock'
```

**Comment by lilydjwg** [comment]
啊啊，0o600 被你写成了 600……

**Comment by petronny** [comment]
啊啊啊我记得我看过0o600还记得躲了一下。。
可能rebase太多了。。
😂😂😂sorry
