### ISSUE TITLE
在lilac.py中增加build这个包的timeout

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/lilac#47]
如题，希望可以
```
depends = ['blah']
timeout = 7200 #2h
```
这样

主要是最近收到了chromium-dev的报错邮件
```
发生未知错误！调用栈如下：

Traceback (most recent call last):
 File "/home/lilydjwg/soft/lilac/lilac", line 174, in build_package
   bindmounts = BIND_MOUNTS,
 File "/home/lilydjwg/soft/lilac/lilaclib.py", line 435, in lilac_build
   call_build_cmd(build_prefix, depend_packages, bindmounts)
 File "/home/lilydjwg/soft/lilac/lilaclib.py", line 464, in call_build_cmd
   build_output = run_cmd(cmd, use_pty=True)
 File "/home/lilydjwg/soft/lilac/lilaclib.py", line 509, in run_cmd
   r = os.read(rfd, 4096)
 File "/home/lilydjwg/scripts/python/pylib/myutils.py", line 175, in timed_out
   raise TimeoutError
TimeoutError
```
然后我在build机上完整build了一遍
```
archlinuxcn-x86_64-build  115740.41s user 4526.14s system 2245% cpu 1:29:16.75 total
```

**Comment by zsrkmyn** [comment]
感觉还应该添加 ccache。

2017年12月22日 上午12:06，"Jingbei Li" <notifications@github.com>写道：

**Comment by lilydjwg** [comment]
lilac 判断失误，已修。普通包的超时时间是 6h，nodejs 的包是 1h。

**Comment by petronny** [comment]
原来如此
不过我觉得根据是不是node的包区分感觉有点怪。。。
感觉所有包都是1h，有需要的手动设置可能更直观一些

**Comment by lilydjwg** [comment]
nodejs 的开发者普遍不那么成熟，曾经遇到一个包，下载文件后因为没有 unzip 工具而失败，被判定为下载失败，并且不断重复下载，在六小时内把一个文件下载了一千多遍……还好文件位于七牛云上，访问速度不怎么样，不然会更疯狂。

手动设置的话，你有兴趣可以 pr 呀。
