### ISSUE TITLE
syringa nvchecker failed after a successful build

### ISSUE THREAD

**Issue by Xuanwo** [archlinuxcn/lilac#94]
[syringa](https://github.com/archlinuxcn/repo/tree/master/syringa) has been built successfully: https://build.archlinuxcn.org/packages/#/syringa

But every time lilac running, I will got an error report:

```
{"logger_name": "nvchecker.core", "name": "syringa", "event": "unexpected error happened", "level": "error"}
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nvchecker/core.py", line 152, in worker
    ret = await get_version(name, conf, keyman=self.keymanager)
  File "/usr/lib/python3.7/site-packages/nvchecker/get_version.py", line 62, in get_version
    version = await func(name, conf, **kwargs)
  File "/usr/lib/python3.7/site-packages/nvchecker/source/github.py", line 24, in get_version
    check_ratelimit(e, name)
  File "/usr/lib/python3.7/site-packages/nvchecker/source/github.py", line 22, in get_version
    return await get_version_real(name, conf, **kwargs)
  File "/usr/lib/python3.7/site-packages/nvchecker/source/github.py", line 64, in get_version_real
    async with session.get(url, headers=headers, **kwargs) as res:
  File "/usr/lib/python3.7/site-packages/nvchecker/source/tornado_httpclient.py", line 62, in __aenter__
    return await to_asyncio_future(client.fetch(self.req))
tornado.httpclient.HTTPClientError: HTTP 404: Not Found
```

I'm not so sure what's wrong with it, can you have a look ?

**Comment by lilydjwg** [comment]
Because there is no release (pre-releases do not count).

**Comment by Xuanwo** [comment]
Well, I got it.

Will nvchecker support an option for fetching pre-releases ?

**Comment by Xuanwo** [comment]
Github do not provide an API for pre-releases, so I changed to use max-tags for a workaround.
